# Final build using MongoDB image
FROM mongo:4.4

# Me
MAINTAINER Josep Quintana

# Set working directory
WORKDIR /PTI

# Get the necessary files [NOT NECESSARY]
COPY ./database/init_database.py .

# Dependencies
RUN mkdir -p /data/db
RUN echo "Ready to start database"

# Start the server command
EXPOSE 27017
CMD ["mongod"]
