# Final build using Python image
FROM python:3.9

# Me
MAINTAINER Josep Quintana

# Set working directory
WORKDIR /PTI

# Install dependencies
COPY ./frontend/requirements.txt .
RUN DEBIAN_FRONTEND=noninteractive pip3.9 install -q -r requirements.txt

# Copy the compiled smart contracts
RUN mkdir -p files/abis/
COPY ./blockchain/abis/BarnaToken.json files/abis/
COPY ./blockchain/abis/FiberToken.json files/abis/
COPY ./blockchain/abis/UpcToken.json files/abis/
COPY ./blockchain/abis/CatToken.json files/abis/
COPY ./blockchain/abis/Escrow.json files/abis/

# Get the necessary files
COPY ./frontend/server_app.py .

# Copy the webapp
RUN mkdir -p www/
COPY ./frontend/www/home.html www/
COPY ./frontend/www/login.html www/
COPY ./frontend/www/signup.html www/
COPY ./frontend/www/favicon.ico www/

# Start the server command
RUN echo "Ready to start frontend"
EXPOSE 80
CMD ["python3.9", "./server_app.py", "-p", "80"]
